language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "veraee-github"
    token:
      secure: "fHWZWSk410UIOS0523UTW7+ISgNAc3gICfyIBWbgxQWr7PSs9JSh3JnjRXi2coRTKQVdvzrr6J44rz/GvBX9pfUvnZ3kFHlTi4tYg2VQENPN+GOZoempLVtLaFa1w1YD5JgkraWyZVHgHYzuxSpIecFm/GeHzTyVLIjoC5D7dbnMLMsP3oPBqJQPstpL/G9U840u7ZKVcP40uNXa2RBElDXRIHsE1C/Vuug2+Rav0ne75apJIaCbaWp/8ClG2Az4Y130s1r5eg3qTv4jIdIee6LRmiHNpO/QQ98qHRIbtWntP9IDa9w9pXK5kxkwaAAfq594+tfzRLICUtIbE4uoJTCA35e4ltczohD/K3mEvMAfRAPI6HHcLcjcO1Hik6L5ROjHV3Vd4V0Hb0hm7vF4wqGdH+2RGGAbK9ueB7ZaOrw/G2x2tKmzsyquaVmH+JlDIAHxtovCA8V4sJxobOvMPrw2yZuKezf+eaim4K4VtPg1Z6ovlxXMTQbZhRfssR19bCUrOFotS2MfrkyQU1w27WaAStGHJ8KiSO7JCMFecOE4USqZiw5k79VEPINxf2IRTNaJxdatD9mmqvauLrFwhKwsDWaqQNa14vy+RXKUIEwd3QywZkFy4YjePshRuWJGeRfRqxn2j8iXMwSdwfXOpY3sHjratw2q2EbLvYu6v0A="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
