language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "veraee-github"
    token:
      secure: "EWOmkBan2FSz9m8uvVfos8dPUZGhpfyRY8ed5KsvG8DGgmv4CgsKoq20nagj3VnLp/qHXX6L27qoaJCMMZEZau8BWXif/eDxh4clAkgn+23N6Mm1pLpBrNaC/PYJX0svixZxw37DjYw4xAMpVmlm5RreS/JIQedMY47k9KwtQK6flN0BUMvguiI7TcHjSCFs98pSo9YFgqLI1N0bnUOqBDwQsFFyMtfTZ0qIk4YyYD9NQPENVFPwtfBFOCPMZ5T1k4g91eYxCh3AaWUfxehOTfZe/x2J8gVYnIeedI5n9ZVecOxfwKpPKinAn/llzrn78QhlD1SmyuauReIfQFJkHcYWnnZ2i6TYxC2sCOMpfLZD8fpUC5UAjAMzkLdnUS+nLtlsUTWBORw8/t9NklNtra6CuJBcQAZYfMLqH5Rin9JV/iyl/fQlNJ0q2kIudD8L7kJOpxCahksyyaHVkHV3ZGVZgZVc8TKN2Y5v/CLI0KC4fvk0FaWQUpBfv9bhC2pGNDDN3nxnkBGh7tmyYerzGPawmBVbwnoHF5ZyCrUpakl04W/M5UceK7QLoQle6Zo+esQ90HFynrHG5Am0zC+VKVt9J8BIG1Hu/Y25gwJwbt0j3Q33Ia0fp2Z3kx+fFd80N3vakJIpyzIE2d+n1w/3JiigKPEQ50BcoGlH7SVyero="

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
